<a href="https://colab.research.google.com/github/YugantGotmare/Machine-Learning-Projects/blob/master/Milk_Quality.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/milknew.csv')

In [3]:
df.head()

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour   Grade
0  6.6          35      1     0     1          0     254    high
1  6.6          36      0     1     0          1     253    high
2  8.5          70      1     1     1          1     246     low
3  9.5          34      1     1     0          1     255     low
4  6.6          37      0     0     0          0     255  medium

In [4]:
df.shape

(1059, 8)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   pH          1059 non-null   float64
 1   Temprature  1059 non-null   int64  
 2   Taste       1059 non-null   int64  
 3   Odor        1059 non-null   int64  
 4   Fat         1059 non-null   int64  
 5   Turbidity   1059 non-null   int64  
 6   Colour      1059 non-null   int64  
 7   Grade       1059 non-null   object 
dtypes: float64(1), int64(6), object(1)
memory usage: 66.3+ KB


In [6]:
df.isnull().sum()

pH            0
Temprature    0
Taste         0
Odor          0
Fat           0
Turbidity     0
Colour        0
Grade         0
dtype: int64

In [7]:
df.describe()

pH   Temprature        Taste         Odor         Fat   \
count  1059.000000  1059.000000  1059.000000  1059.000000  1059.000000   
mean      6.630123    44.226629     0.546742     0.432483     0.671388   
std       1.399679    10.098364     0.498046     0.495655     0.469930   
min       3.000000    34.000000     0.000000     0.000000     0.000000   
25%       6.500000    38.000000     0.000000     0.000000     0.000000   
50%       6.700000    41.000000     1.000000     0.000000     1.000000   
75%       6.800000    45.000000     1.000000     1.000000     1.000000   
max       9.500000    90.000000     1.000000     1.000000     1.000000   

         Turbidity       Colour  
count  1059.000000  1059.000000  
mean      0.491029   251.840415  
std       0.500156     4.307424  
min       0.000000   240.000000  
25%       0.000000   250.000000  
50%       0.000000   255.000000  
75%       1.000000   255.000000  
max       1.000000   255.000000

In [8]:
df.corr()

pH  Temprature     Taste      Odor      Fat   Turbidity  \
pH          1.000000    0.244684 -0.064053 -0.081331 -0.093429   0.048384   
Temprature  0.244684    1.000000 -0.109792 -0.048870  0.024073   0.185106   
Taste      -0.064053   -0.109792  1.000000  0.017582  0.324149   0.055755   
Odor       -0.081331   -0.048870  0.017582  1.000000  0.314505   0.457935   
Fat        -0.093429    0.024073  0.324149  0.314505  1.000000   0.329264   
Turbidity   0.048384    0.185106  0.055755  0.457935  0.329264   1.000000   
Colour     -0.164565   -0.008511 -0.082654 -0.039361  0.114151   0.136436   

              Colour  
pH         -0.164565  
Temprature -0.008511  
Taste      -0.082654  
Odor       -0.039361  
Fat         0.114151  
Turbidity   0.136436  
Colour      1.000000

In [9]:
df.loc[df["Grade"] == 'high', "Grade"] = 2
df.loc[df["Grade"] == 'medium', "Grade"] = 1
df.loc[df["Grade"] == 'low', "Grade"] = 0

In [10]:
df.head()

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour Grade
0  6.6          35      1     0     1          0     254     2
1  6.6          36      0     1     0          1     253     2
2  8.5          70      1     1     1          1     246     0
3  9.5          34      1     1     0          1     255     0
4  6.6          37      0     0     0          0     255     1

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   pH          1059 non-null   float64
 1   Temprature  1059 non-null   int64  
 2   Taste       1059 non-null   int64  
 3   Odor        1059 non-null   int64  
 4   Fat         1059 non-null   int64  
 5   Turbidity   1059 non-null   int64  
 6   Colour      1059 non-null   int64  
 7   Grade       1059 non-null   object 
dtypes: float64(1), int64(6), object(1)
memory usage: 66.3+ KB


In [12]:
df["Grade"] = df["Grade"].astype(str).astype(int)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1059 entries, 0 to 1058
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   pH          1059 non-null   float64
 1   Temprature  1059 non-null   int64  
 2   Taste       1059 non-null   int64  
 3   Odor        1059 non-null   int64  
 4   Fat         1059 non-null   int64  
 5   Turbidity   1059 non-null   int64  
 6   Colour      1059 non-null   int64  
 7   Grade       1059 non-null   int64  
dtypes: float64(1), int64(7)
memory usage: 66.3 KB


In [14]:
x = df.drop(columns=['Grade'])
y = df['Grade']

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10)

In [17]:
x_train.shape, x_test.shape, y_train.shape, y_test.shape

((847, 7), (212, 7), (847,), (212,))

In [18]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import make_scorer, accuracy_score, roc_auc_score
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [19]:
model_1 = LogisticRegression()
model_1.fit(x_train,y_train)

/usr/local/lib/python3.8/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [20]:
y_predict =model_1.predict(x_test)
y_predict

array([1, 2, 0, 1, 2, 1, 1, 1, 0, 2, 2, 1, 2, 2, 1, 1, 0, 0, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 2, 1, 1, 2, 2, 0, 1, 0, 0, 2,
       1, 1, 1, 0, 2, 2, 0, 2, 1, 2, 2, 1, 0, 0, 1, 2, 0, 2, 0, 0, 2, 0,
       2, 2, 1, 1, 0, 0, 2, 0, 1, 2, 1, 2, 0, 0, 2, 1, 2, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 2, 1, 1, 1, 2, 2, 0, 2, 1, 0, 1, 0, 0, 1, 0, 2, 1,
       1, 0, 2, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 2, 1, 0, 0,
       0, 1, 2, 0, 1, 2, 0, 0, 0, 1, 2, 1, 1, 2, 1, 1, 0, 0, 1, 2, 0, 1,
       1, 1, 2, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 2, 2, 1, 1, 1, 2, 0, 1,
       1, 1, 0, 0, 2, 0, 1, 0, 2, 1, 2, 1, 1, 0, 1, 1, 0, 0, 0, 2, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 1, 2, 0, 1, 0, 2, 1])

In [21]:
confusion_matrix(y_test, y_predict)

array([[58,  9, 14],
       [ 6, 65,  1],
       [14, 13, 32]])

In [22]:
model_1.score(x_train,y_train)

0.7497048406139315

In [23]:
model_1.score(x_test,y_test)

0.7311320754716981

In [24]:
LR_Predict = model_1.predict(x_train)
LR_Accuracy = accuracy_score(y_train, LR_Predict)
print("Accuracy: " + str(LR_Accuracy))

Accuracy: 0.7497048406139315


In [26]:
resultlor = classification_report(y_test, y_predict)
print(resultlor)

              precision    recall  f1-score   support

           0       0.74      0.72      0.73        81
           1       0.75      0.90      0.82        72
           2       0.68      0.54      0.60        59

    accuracy                           0.73       212
   macro avg       0.72      0.72      0.72       212
weighted avg       0.73      0.73      0.72       212



In [27]:
model_2 = RandomForestClassifier()
model_2.fit(x_train, y_train)

RandomForestClassifier()

In [28]:
y_predicts =model_2.predict(x_test)
y_predicts

array([1, 0, 0, 1, 0, 1, 2, 1, 0, 2, 2, 0, 2, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 2, 1, 1, 2, 2, 0, 1, 2, 1, 2,
       2, 0, 1, 0, 0, 2, 0, 2, 2, 2, 2, 1, 0, 0, 1, 2, 2, 2, 0, 2, 0, 0,
       0, 2, 1, 1, 2, 0, 2, 0, 2, 0, 1, 2, 0, 0, 2, 0, 2, 2, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 2, 1, 2, 1, 2, 0, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2, 1,
       1, 0, 0, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1, 0, 2, 1, 2, 0, 2, 1, 0, 0,
       2, 1, 0, 0, 0, 2, 0, 2, 0, 1, 0, 1, 1, 2, 1, 1, 0, 0, 0, 1, 2, 1,
       2, 1, 2, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 1, 1, 1, 2, 1, 1,
       1, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 0, 1, 0, 0, 1, 2, 0, 0, 2, 2, 1,
       1, 2, 1, 0, 0, 1, 2, 1, 2, 0, 1, 1, 0, 0])

In [29]:
print(confusion_matrix(y_test, y_predicts))

[[80  1  0]
 [ 0 72  0]
 [ 0  1 58]]


In [30]:
model_2.score(x_train,y_train)

1.0

In [31]:
model_2.score(x_test,y_test)

0.9905660377358491

In [32]:
resultRFC = classification_report(y_test, y_predicts)
print(resultRFC)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99        81
           1       0.97      1.00      0.99        72
           2       1.00      0.98      0.99        59

    accuracy                           0.99       212
   macro avg       0.99      0.99      0.99       212
weighted avg       0.99      0.99      0.99       212



In [33]:
RFC_Predict = model_2.predict(x_train)
RFC_Accuracy = accuracy_score(y_train, RFC_Predict)
print("Accuracy: " + str(RFC_Accuracy))

Accuracy: 1.0


In [34]:
model_3 = KNeighborsClassifier()
model_3.fit(x_train, y_train)

KNeighborsClassifier()

In [35]:
y_predicts =model_3.predict(x_test)
y_predicts

array([1, 0, 0, 1, 0, 1, 2, 1, 0, 2, 2, 0, 2, 1, 1, 1, 0, 1, 2, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 2, 1, 1, 2, 2, 0, 1, 2, 1, 2,
       2, 0, 1, 0, 0, 2, 0, 2, 2, 2, 2, 1, 0, 0, 1, 2, 2, 2, 0, 2, 0, 0,
       0, 2, 1, 1, 2, 0, 2, 0, 2, 0, 1, 2, 0, 0, 2, 0, 2, 2, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 2, 1, 2, 1, 2, 0, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2, 1,
       1, 0, 0, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1, 0, 2, 1, 2, 0, 2, 1, 0, 0,
       2, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0, 1, 1, 2, 1, 2, 0, 0, 0, 1, 2, 1,
       2, 1, 2, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 1, 1, 1, 2, 1, 1,
       1, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 0, 1, 0, 0, 1, 2, 0, 0, 2, 2, 1,
       1, 2, 1, 0, 0, 1, 2, 1, 2, 0, 1, 2, 0, 0])

In [36]:
print(confusion_matrix(y_test, y_predicts))

[[79  2  0]
 [ 0 71  1]
 [ 0  1 58]]


In [37]:
model_3.score(x_train,y_train)

0.9952774498229043

In [38]:
model_3.score(x_test,y_test)

0.9811320754716981

In [39]:
resultKNN = classification_report(y_test, y_predicts)
print(resultKNN)

              precision    recall  f1-score   support

           0       1.00      0.98      0.99        81
           1       0.96      0.99      0.97        72
           2       0.98      0.98      0.98        59

    accuracy                           0.98       212
   macro avg       0.98      0.98      0.98       212
weighted avg       0.98      0.98      0.98       212



In [40]:
KNN_Predict = model_3.predict(x_train)
KNN_Accuracy = accuracy_score(y_train, KNN_Predict)
print("Accuracy: " + str(KNN_Accuracy))

Accuracy: 0.9952774498229043


In [41]:
model_4 = DecisionTreeClassifier()
model_4.fit(x_train, y_train)

DecisionTreeClassifier()

In [42]:
y_predicts =model_4.predict(x_test)
y_predicts

array([1, 0, 0, 1, 0, 1, 2, 1, 0, 2, 2, 0, 2, 0, 1, 1, 0, 1, 2, 1, 1, 1,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 2, 1, 1, 2, 2, 0, 1, 2, 1, 2,
       2, 0, 1, 0, 0, 2, 0, 2, 2, 2, 2, 1, 0, 0, 1, 2, 2, 2, 0, 2, 0, 0,
       0, 2, 1, 1, 2, 0, 2, 0, 2, 0, 1, 2, 0, 0, 2, 0, 2, 2, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 2, 1, 2, 1, 2, 0, 0, 2, 1, 0, 2, 0, 0, 1, 0, 2, 1,
       1, 0, 0, 1, 1, 2, 0, 2, 1, 0, 1, 1, 1, 0, 2, 1, 2, 0, 2, 1, 0, 0,
       2, 1, 0, 0, 0, 1, 0, 2, 0, 1, 0, 1, 1, 2, 1, 1, 0, 0, 0, 1, 2, 1,
       2, 1, 2, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 2, 0, 1, 1, 1, 2, 1, 1,
       1, 2, 0, 0, 0, 0, 1, 0, 2, 2, 2, 0, 1, 0, 0, 1, 2, 0, 0, 2, 2, 1,
       1, 2, 1, 0, 0, 1, 2, 1, 2, 0, 1, 1, 0, 0])

In [43]:
print(confusion_matrix(y_test, y_predicts))

[[80  1  0]
 [ 0 72  0]
 [ 0  2 57]]


In [44]:
model_4.score(x_train,y_train)

1.0

In [45]:
model_4.score(x_test,y_test)

0.9858490566037735

In [46]:
resultDT = classification_report(y_test, y_predicts)
print(resultDT)

              precision    recall  f1-score   support

           0       1.00      0.99      0.99        81
           1       0.96      1.00      0.98        72
           2       1.00      0.97      0.98        59

    accuracy                           0.99       212
   macro avg       0.99      0.98      0.99       212
weighted avg       0.99      0.99      0.99       212



In [47]:
DT_Predict = model_4.predict(x_train)
DT_Accuracy = accuracy_score(y_train, DT_Predict)
print("Accuracy: " + str(DT_Accuracy))

Accuracy: 1.0


In [48]:
model_performance_accuracy = pd.DataFrame({'Model': ['LogisticRegression', 'RandomForestClassifier', 'KNeighborsClassifier','DecisionTreeClassifier'],
                                           'Accuracy':[LR_Accuracy, RFC_Accuracy, KNN_Accuracy, DT_Accuracy]})

In [49]:
model_performance_accuracy.sort_values('Accuracy', ascending=False)

Model  Accuracy
1  RandomForestClassifier  1.000000
3  DecisionTreeClassifier  1.000000
2    KNeighborsClassifier  0.995277
0      LogisticRegression  0.749705

In [50]:
df.sample(5)

pH  Temprature  Taste  Odor  Fat   Turbidity  Colour  Grade
310  6.6          37      1     1     1          1     255      2
735  5.6          50      0     1     1          1     255      0
597  5.5          45      1     0     1          1     250      0
168  8.6          55      0     1     0          0     255      0
618  6.6          50      0     0     0          1     250      0

In [54]:
output=model_3.predict([[6.6,37,1,1,1,1,255]])

/usr/local/lib/python3.8/dist-packages/sklearn/base.py:420: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [55]:
if output == 2:
  print("The milk quality is 'Good'")
if output == 1:
  print("The milk quality is 'Moderate'")
if output == 0:
  print("The milk quality is 'Bad'")

The milk quality is 'Good'
